sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qwe123
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: sky-takeout-xiaocapetian
    accessKeyId: LTAI5tJ2irdd8RwgnJzoKpT4
    accessKeySecret: nDMSiT939LUptIdgxG3JkUi91iupOY
  redis:
    host:localhost
    port:6379
    database:0
  wechat:
    appid: wx60a30bc662becf2f
    secret: fc9a90146e6f4cb718c0d02bc19310d2
    #以下是微信支付的
    mchid: 1561414331
    mchserialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDUV3
    weChatPayCertFilePath: D:\pay\wechatpay\166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6619cf50.r6.cpolar.top/notify/paysuccess
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundsuccess